### ISSUE TITLE
issue in pom.xml file

### ISSUE THREAD

**Issue by umairq** [lapaesleme/ckan2void#2]
Hi there:
I am facing an issue in pom.xml file of this project. It can not import the eu.trentorise.opendata:jackan library. I am using ubuntu operating system. 
Following is the error it shows:
Missing artifact eu.trentorise.opendata:jackan:jar:0.4.3-SNAPSHOT
Please help me resolve this issue.
Also please provide an example config ttl file. 
thanks

**Comment by lapaesleme** [comment]
Hi Umair!

Please, could you be more specific about the issues?

The only thing I can imagine that you could have problems with is the dependency “jckan” (https://github.com/opendatatrentino/jackan) in the pom.xml.

In order to build the ckan2rdf project you have to download the jckan project and build it. Thats all. After building jckan, Maven will place its library in Maven’s library to be used in the building of ckan2rdf.

However, to build the jckan project, there are some steps to setup the test resources. To avoid this setup, assuming that we do not need to test the jckan project, I always removed the test classes before building it.

Best regards,

Luiz André

**Comment by umairq** [comment]
Thankyou for prompt reply Luiz, your suggestion fixed my issue. I was missing the Jackson build. I think build version in pom.xml is not correct and its better to add some instructions in readme file(Just a suggestion). Thankyou. Will let you know If i will face any issue in future.

**Comment by umairq** [comment]
Hi Luiz:
I got into another issue, when I run the Main file it gives the following error.

2019-10-16 20:56:06 ERROR error:117 - Save VoID + VoIDComp failure (<http://localhost:3030/resource/1980-1989-pb-daily-summary-concentrations-virginia-beach-norfolk-newport-news-va-nc-cbsa-datahub>). Msg: null

do we need to add any dataset on fuseki server? 
Please tell me what kind of database server we need to install and what database we need to create on that server?
I install postgres and fuseki server, created to empty databases (datasetDescription and Temp) on postgres.
Please guide me.
Thanks
Any

**Comment by umairq** [comment]
Yes thank you for explanation Luiz. It is quite helpful in understanding overall scenario. I will be happy to hear more about the config file. 
I ran the code but when it comes to saving the void file in (saveVoid(_void, _voidComp, datasetUri, graphUri)) function it gives error. I think there is still some configuration issue which is missing. If you elaborate more about config files and data folder in project (purpose of that folder and how to utilize it), I will be able to fix the issue. 
Thanks

**Comment by lapaesleme** [comment]
Hi Umair!


I am back to help you with the configurations. I just updated some things in cka2void on GitHub, so please UPDATE your clone copy of ckan2void.

1) Download and run Apache Jena Fuseki (https://jena.apache.org/download/index.cgi <https://jena.apache.org/download/index.cgi>). It must be run such that its endpoint is http://localhost:3030 <http://localhost:3030/>. The default installation already sets up Fuseki this way.
2) Create the datasets DatasetDescriptions and Temp in Fuseki
3) Run PostgreSQL. It. Just be 
4) Create the datasets DatasetDescriptions and Temp in Postgres.
5) Copy the following files from ckan2void/resources/conf to the same directory
	host.template.properties to host.properties
	sdb1.template.ttl to sdb1.ttl
	sdb2.template.ttl to sdb2.ttl
6) update your postgres password in sdb1.ttl and sdb2.ttl
7) run Main.java

It must solve your issues. You’ll find the datasets metadata in the “edit” tab at http://localhost:3030/dataset.html?tab=query&ds=/DatasetDescriptions <http://localhost:3030/dataset.html?tab=query&ds=/DatasetDescriptions>.


Please, let us know wether you succeeded or not.

Best wishes!!

**Comment by umairq** [comment]
Thankyou so much for your support Luiz. I became able to successfully run the project and generate DatasetDescription.nq file from it. 
Now as a next step I am trying to run dataset-search([https://github.com/lapaesleme/dataset-search]) I will post the issue if i feel any problem.

Cheers
